sudo: required
dist: trusty
language: coq
cache:
  apt: true
branches:
  only:
  - master
env:
  matrix:
  - COQ="8.6.1" MATHCOMP="1.7.0"
  - COQ="8.7.2" MATHCOMP="1.7.0"
  - COQ="8.8.1" MATHCOMP="1.7.0"
  - COQ="8.8.1" MATHCOMP="dev"
  - COQ="dev"   MATHCOMP="1.7.0"
  - COQ="dev"   MATHCOMP="dev"
install:
- docker pull strubpy/coq:${COQ}-mathcomp-${MATHCOMP}
- docker tag  strubpy/coq:${COQ}-mathcomp-${MATHCOMP} ci:current
- docker run  -itd --name CI -v $PWD:/home/ci/multinomials ci:current
- docker exec CI sh -c 'opam pin add -n multinomials'
- docker exec CI sh -c 'opam install -vvv --deps-only coq-mathcomp-multinomials'
script:
- docker exec CI sh -c 'opam install -vvv coq-mathcomp-multinomials'
