sudo: required
dist: trusty
language: coq
branches:
  only:
  - master
services:
- docker
before_install:
- docker pull strubpy/coq:ssr-dev
script:
- >-
  docker run -v $PWD:/home/ci/multinomials strubpy/coq:ssr-dev
  sh -c 'cd multinomials && opam config exec -- make'
